---
development:
  cloud_name: 'dinary'
  api_key: '417279957534413'
  api_secret: 'YnTHkm0UX5SRNbHNeM7tyBysXXY'
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: 'dinary'
  api_key: '417279957534413'
  api_secret: 'YnTHkm0UX5SRNbHNeM7tyBysXXY'
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: 'dinary'
  api_key: '417279957534413'
  api_secret: 'YnTHkm0UX5SRNbHNeM7tyBysXXY'
  enhance_image_tag: true
  static_image_support: false
